apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-assessment-dev-app-deploy"
    # This will be populated by Terraform outputs
  labels:
    app: demo-app
